### PR TITLE
Issue 111: NULL Pointer exceptions on startup

### LINKED ISSUE #111: NULL Pointer exceptions on startup
Could be a side-effect of the VersionOne authentication 401.
```
java.lang.NullPointerException
  at edu.tamu.app.cache.service.ActiveSprintsScheduledCacheService.lambda$fetchActiveSprints$3(ActiveSprintsScheduledCacheService.java:94)
  at java.lang.Iterable.forEach(Iterable.java:75)
  at edu.tamu.app.cache.service.ActiveSprintsScheduledCacheService.fetchActiveSprints(ActiveSprintsScheduledCacheService.java:91)
  at edu.tamu.app.cache.service.ActiveSprintsScheduledCacheService.lambda$update$0(ActiveSprintsScheduledCacheService.java:46)
  at java.util.ArrayList.forEach(ArrayList.java:1259)
  at edu.tamu.app.cache.service.ActiveSprintsScheduledCacheService.update(ActiveSprintsScheduledCacheService.java:45)
  at edu.tamu.app.cache.service.AbstractScheduledCacheService.schedule(AbstractScheduledCacheService.java:27)
  at edu.tamu.app.cache.service.ActiveSprintsScheduledCacheService.schedule(ActiveSprintsScheduledCacheService.java:39)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by kaladay**
The boolean logic is reversed, resulting in the NULL pointer exception on startup.
This also seems to prevent the cache from working after startup for existing Remote Projects.
(Newly created Remote Projects will cache properly.)

Also change the logic to use nested if conditions instead of `return` appears to solve the problem.

resolves #111

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Should probably use StringUtils.isNotEmpty instead of creating an optional. It will also ensure it is not an empty string.

File: src/main/java/edu/tamu/app/ProjectInitialization.java [hunk 1]
```diff
@@ -30,15 +30,11 @@
     @Override
     public void run(String... args) throws Exception {
         remoteProjectManagerRepo.findAll().forEach(versionManagementSoftware -> {
-            if (Optional.ofNullable( versionManagementSoftware.getUrl()).isPresent()) {
-                return;
+            if (Optional.ofNullable(versionManagementSoftware.getUrl()).isPresent()) {
```
Comment (ghost) [inline src/main/java/edu/tamu/app/ProjectInitialization.java]: Why not combine the conditionals?

**Review by ghost — APPROVED** [review]
